version: '3.9'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data_mongo:/data/db
    restart: always
    networks:
      - app_net
  
  be:
    build: ./be
    volumes:
      - ./be:/app
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/employee
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      - app_net

  fe:
    build: ./fe
    volumes:
      - ./fe:/app
    environment:
      - VITE_API_URL=http://localhost:5000
    ports:
      - 5173:5173
    depends_on:
      - be

networks:
  app_net:

volumes:
  data_mongo: